# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x03\x64ht\"\x1c\n\nIntRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1e\n\x0bIntResponse\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\x04Node\x12.\n\x07SendInt\x12\x0f.dht.IntRequest\x1a\x10.dht.IntResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTREQUEST']._serialized_start=21
  _globals['_INTREQUEST']._serialized_end=49
  _globals['_INTRESPONSE']._serialized_start=51
  _globals['_INTRESPONSE']._serialized_end=81
  _globals['_NODE']._serialized_start=83
  _globals['_NODE']._serialized_end=137
# @@protoc_insertion_point(module_scope)
