# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dht.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdht.proto\x12\x03\x64ht\",\n\x0bJoinRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\x1f\n\x0cJoinResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\x11UpdateNodeRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"%\n\x12UpdateNodeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"+\n\x18UpdatePredecessorRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\",\n\x19UpdatePredecessorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x15UpdateSucessorRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\")\n\x16UpdateSucessorResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x10NodeQueryRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\";\n\x11NodeQueryResponse\x12\x11\n\tsuccessor\x18\x01 \x01(\x05\x12\x13\n\x0bpredecessor\x18\x02 \x01(\x05\"\x1c\n\nIntRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"\x1e\n\x0bIntResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"*\n\x0bHashRequest\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05\"\x1f\n\x0cHashResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb3\x03\n\x04Node\x12+\n\x04Join\x12\x10.dht.JoinRequest\x1a\x11.dht.JoinResponse\x12:\n\tQueryNode\x12\x15.dht.NodeQueryRequest\x1a\x16.dht.NodeQueryResponse\x12=\n\nUpdateNode\x12\x16.dht.UpdateNodeRequest\x1a\x17.dht.UpdateNodeResponse\x12R\n\x11UpdatePredecessor\x12\x1d.dht.UpdatePredecessorRequest\x1a\x1e.dht.UpdatePredecessorResponse\x12I\n\x0eUpdateSucessor\x12\x1a.dht.UpdateSucessorRequest\x1a\x1b.dht.UpdateSucessorResponse\x12.\n\x07SendInt\x12\x0f.dht.IntRequest\x1a\x10.dht.IntResponse\"\x00\x12\x34\n\x0bReceiveHash\x12\x10.dht.HashRequest\x1a\x11.dht.HashResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINREQUEST']._serialized_start=18
  _globals['_JOINREQUEST']._serialized_end=62
  _globals['_JOINRESPONSE']._serialized_start=64
  _globals['_JOINRESPONSE']._serialized_end=95
  _globals['_UPDATENODEREQUEST']._serialized_start=97
  _globals['_UPDATENODEREQUEST']._serialized_end=133
  _globals['_UPDATENODERESPONSE']._serialized_start=135
  _globals['_UPDATENODERESPONSE']._serialized_end=172
  _globals['_UPDATEPREDECESSORREQUEST']._serialized_start=174
  _globals['_UPDATEPREDECESSORREQUEST']._serialized_end=217
  _globals['_UPDATEPREDECESSORRESPONSE']._serialized_start=219
  _globals['_UPDATEPREDECESSORRESPONSE']._serialized_end=263
  _globals['_UPDATESUCESSORREQUEST']._serialized_start=265
  _globals['_UPDATESUCESSORREQUEST']._serialized_end=305
  _globals['_UPDATESUCESSORRESPONSE']._serialized_start=307
  _globals['_UPDATESUCESSORRESPONSE']._serialized_end=348
  _globals['_NODEQUERYREQUEST']._serialized_start=350
  _globals['_NODEQUERYREQUEST']._serialized_end=385
  _globals['_NODEQUERYRESPONSE']._serialized_start=387
  _globals['_NODEQUERYRESPONSE']._serialized_end=446
  _globals['_INTREQUEST']._serialized_start=448
  _globals['_INTREQUEST']._serialized_end=476
  _globals['_INTRESPONSE']._serialized_start=478
  _globals['_INTRESPONSE']._serialized_end=508
  _globals['_HASHREQUEST']._serialized_start=510
  _globals['_HASHREQUEST']._serialized_end=552
  _globals['_HASHRESPONSE']._serialized_start=554
  _globals['_HASHRESPONSE']._serialized_end=585
  _globals['_NODE']._serialized_start=588
  _globals['_NODE']._serialized_end=1023
# @@protoc_insertion_point(module_scope)
